name: ci-kerberos-kinit
run-name: Kerberos Kinit CI triggered by @${{ github.actor }}

on:
  schedule:
    - cron: "0 5 * * *"
  push:
    branches:
      - "dev"
    tags:
      - "v*.*.*"

jobs:
  eds-base-notebook:
    uses: "aphp/ci-workflows/.github/workflows/container-ci.yml@dev"
    with:
      dockerfile-path: "Dockerfile"
      image-name: "ghcr.io/aphp/kerberos-kinit"
      hadolint-ignore: "DL3008"
      dockle-ignore: "CIS-DI-0010"